insert into public.events (
  title,
  slug,
  description,
  event_date,
  start_time,
  end_time,
  location_name,
  address,
  application_deadline,
  application_fee,
  applications_enabled,
  vendor_capacity,
  status,
  published
) values (
  '702Market Night Market',
  'october-night-market',
  'An after-dark gathering of vintage hunters, local makers, collectors, and hungry shoppers in the heart of Las Vegas.',
  '2026-10-24',
  '16:00',
  '22:00',
  'Downtown Las Vegas',
  'Downtown Las Vegas, NV',
  '2026-10-10',
  50,
  true,
  null,
  'upcoming',
  true
)
on conflict (slug) do update set
  title = excluded.title,
  description = excluded.description,
  event_date = excluded.event_date,
  start_time = excluded.start_time,
  end_time = excluded.end_time,
  location_name = excluded.location_name,
  address = excluded.address,
  application_deadline = excluded.application_deadline,
  application_fee = excluded.application_fee,
  applications_enabled = excluded.applications_enabled,
  vendor_capacity = excluded.vendor_capacity,
  status = excluded.status,
  published = excluded.published,
  updated_at = now();
