insert into public.events (
  title,
  slug,
  description,
  event_date,
  start_time,
  end_time,
  location_name,
  address,
  application_deadline,
  application_fee,
  applications_enabled,
  vendor_capacity,
  status,
  published
) values
  (
    '702Market Night Market',
    'october-night-market',
    'An after-dark gathering of vintage hunters, local makers, collectors, and hungry shoppers in the heart of Las Vegas.',
    '2026-10-24',
    '16:00',
    '22:00',
    'Downtown Las Vegas',
    'Downtown Las Vegas, NV',
    '2026-10-10',
    50,
    true,
    72,
    'upcoming',
    true
  ),
  (
    'Pink Pony Pop-Up',
    'pink-pony-pop-up',
    'A candy-colored vendor night for accessories, handmade goods, and playful vintage finds.',
    '2026-11-14',
    '15:00',
    '21:00',
    'Arts District Courtyard',
    '1025 S 1st St, Las Vegas, NV',
    '2026-10-31',
    45,
    true,
    48,
    'upcoming',
    true
  ),
  (
    'Holiday Mini Market',
    'holiday-mini-market',
    'A compact holiday shopping market with giftable art, baked goods, jewelry, and local brands.',
    '2026-12-12',
    '12:00',
    '18:00',
    'Fergusons Downtown',
    '1028 Fremont St, Las Vegas, NV',
    '2026-11-28',
    65,
    true,
    60,
    'upcoming',
    true
  ),
  (
    'Sweetheart Swap',
    'sweetheart-swap',
    'A February market for date-night outfits, handmade cards, flowers, sweets, and secondhand treasures.',
    '2027-02-07',
    '13:00',
    '19:00',
    'The Gather House',
    'Downtown Las Vegas, NV',
    '2027-01-20',
    55,
    true,
    52,
    'upcoming',
    true
  ),
  (
    'Summer Sidewalk Market',
    'summer-sidewalk-market',
    'A warm-weather community market with cold drinks, vintage racks, art prints, and local DJs.',
    '2026-07-18',
    '17:00',
    '22:00',
    'Container Park',
    '707 Fremont St, Las Vegas, NV',
    '2026-07-01',
    40,
    false,
    40,
    'completed',
    true
  )
on conflict (slug) do update set
  title = excluded.title,
  description = excluded.description,
  event_date = excluded.event_date,
  start_time = excluded.start_time,
  end_time = excluded.end_time,
  location_name = excluded.location_name,
  address = excluded.address,
  application_deadline = excluded.application_deadline,
  application_fee = excluded.application_fee,
  applications_enabled = excluded.applications_enabled,
  vendor_capacity = excluded.vendor_capacity,
  status = excluded.status,
  published = excluded.published,
  updated_at = now();

delete from public.applications
where email like '%@example.test';

insert into public.applications (
  event_id,
  first_name,
  last_name,
  email,
  phone,
  business_name,
  instagram,
  website,
  category,
  product_description,
  price_range,
  booth_type,
  electricity_required,
  special_requests,
  status,
  admin_notes,
  application_fee,
  payment_status,
  payment_reference,
  paid_at,
  created_at
)
select
  events.id,
  vendors.first_name,
  vendors.last_name,
  vendors.email,
  vendors.phone,
  vendors.business_name,
  vendors.instagram,
  vendors.website,
  vendors.category,
  vendors.product_description,
  vendors.price_range,
  vendors.booth_type,
  vendors.electricity_required,
  vendors.special_requests,
  vendors.status::public.application_status,
  vendors.admin_notes,
  events.application_fee,
  vendors.payment_status::public.payment_status,
  vendors.payment_reference,
  vendors.paid_at,
  vendors.created_at
from (
  values
    ('october-night-market', 'Mina', 'Reyes', 'mina.reyes@example.test', '702-555-0101', 'Desert Bloom Vintage', '@desertbloomvintage', 'https://example.test/desert-bloom', 'Vintage', 'Curated 90s and Y2K dresses, denim, and statement jackets.', '$18 - $120', 'standard', false, 'Corner placement if possible for rolling rack flow.', 'approved', 'Strong fit for the brand mix.', 'paid', 'FAKE-1001', now() - interval '3 days', now() - interval '14 days'),
    ('october-night-market', 'Jules', 'Kim', 'jules.kim@example.test', '702-555-0102', 'Lucky Cat Charms', '@luckycatcharms', null, 'Accessories', 'Phone charms, keychains, sticker sheets, and handmade bag clips.', '$5 - $35', 'standard', false, null, 'pending', null, 'unpaid', null, null, now() - interval '13 days'),
    ('october-night-market', 'Tasha', 'Brooks', 'tasha.brooks@example.test', '702-555-0103', 'Chrome Rose Jewelry', '@chromerosejewelry', 'https://example.test/chrome-rose', 'Jewelry', 'Silver-tone chains, charm necklaces, rings, and custom initials.', '$20 - $95', 'standard', false, 'Needs one chair behind table.', 'approved', 'Approved for jewelry category.', 'paid', 'FAKE-1002', now() - interval '2 days', now() - interval '12 days'),
    ('october-night-market', 'Nico', 'Santos', 'nico.santos@example.test', '702-555-0104', 'After Hours Prints', '@afterhoursprints', null, 'Art', 'Risograph-style prints, mini posters, zines, and postcards.', '$4 - $45', 'shared', false, 'Happy to share with another art vendor.', 'waitlisted', 'Great work, hold for layout.', 'unpaid', null, null, now() - interval '11 days'),
    ('october-night-market', 'Ari', 'Valdez', 'ari.valdez@example.test', '702-555-0105', 'Snack Star LV', '@snackstarlv', 'https://example.test/snack-star', 'Food', 'Packaged sweet-and-spicy snack mixes and aguas frescas.', '$6 - $18', 'standard', true, 'Needs access to one outlet.', 'pending', null, 'unpaid', null, null, now() - interval '10 days'),
    ('october-night-market', 'Bea', 'Martinez', 'bea.martinez@example.test', '702-555-0106', 'Tiny Shrine Studio', '@tinyshrinestudio', null, 'Handmade', 'Clay trinket dishes, miniature altar pieces, magnets, and charms.', '$8 - $60', 'standard', false, null, 'declined', 'Category is full for October.', 'refunded', 'FAKE-1003', now() - interval '6 days', now() - interval '9 days'),
    ('pink-pony-pop-up', 'Lena', 'Fox', 'lena.fox@example.test', '702-555-0107', 'Velvet Lasso', '@velvetlasso', 'https://example.test/velvet-lasso', 'Clothing', 'Playful western-inspired secondhand clothing and rhinestone belts.', '$15 - $85', 'standard', false, null, 'approved', null, 'paid', 'FAKE-1004', now() - interval '1 day', now() - interval '8 days'),
    ('pink-pony-pop-up', 'Sam', 'Patel', 'sam.patel@example.test', '702-555-0108', 'Peach Fuzz Goods', '@peachfuzzgoods', null, 'Beauty', 'Lip oils, body shimmer, nail decals, and handmade soap.', '$7 - $30', 'standard', false, 'Sensitive to direct sun if outdoors.', 'pending', null, 'unpaid', null, null, now() - interval '7 days'),
    ('pink-pony-pop-up', 'Gia', 'Tran', 'gia.tran@example.test', '702-555-0109', 'Mood Ring Market', '@moodringmarket', 'https://example.test/mood-ring', 'Collectibles', 'Blind boxes, toy collectibles, trading cards, and display cases.', '$5 - $70', 'shared', false, null, 'waitlisted', 'Potential duplicate category.', 'unpaid', null, null, now() - interval '6 days'),
    ('pink-pony-pop-up', 'Omar', 'Hale', 'omar.hale@example.test', '702-555-0110', 'Heatwave Hats', '@heatwavehats', null, 'Accessories', 'Embroidered caps, beanies, and custom patches.', '$22 - $48', 'standard', false, null, 'approved', null, 'paid', 'FAKE-1005', now() - interval '1 day', now() - interval '6 days'),
    ('pink-pony-pop-up', 'Ruby', 'Chen', 'ruby.chen@example.test', '702-555-0111', 'Sugar Glass Studio', '@sugarglassstudio', 'https://example.test/sugar-glass', 'Art', 'Stained-glass minis, sun catchers, and window ornaments.', '$18 - $140', 'standard', false, 'Needs wall or grid display approval.', 'pending', null, 'unpaid', null, null, now() - interval '5 days'),
    ('holiday-mini-market', 'Dani', 'Ortega', 'dani.ortega@example.test', '702-555-0112', 'Paper Moon Press', '@papermoonpress', null, 'Art', 'Holiday cards, calendars, prints, gift tags, and wrapping sheets.', '$4 - $38', 'standard', false, null, 'approved', 'Holiday fit.', 'paid', 'FAKE-1006', now() - interval '2 hours', now() - interval '4 days'),
    ('holiday-mini-market', 'Noelle', 'King', 'noelle.king@example.test', '702-555-0113', 'Candle Crush Co', '@candlecrushco', 'https://example.test/candle-crush', 'Handmade', 'Small-batch candles, wax melts, room sprays, and gift bundles.', '$10 - $55', 'standard', false, null, 'approved', null, 'paid', 'FAKE-1007', now() - interval '3 hours', now() - interval '4 days'),
    ('holiday-mini-market', 'Ivy', 'Morgan', 'ivy.morgan@example.test', '702-555-0114', 'The Glitter Bakery', '@theglitterbakery', null, 'Food', 'Cupcakes, decorated cookies, cake jars, and seasonal sweets.', '$5 - $42', 'standard', true, 'Needs food vendor placement.', 'pending', null, 'unpaid', null, null, now() - interval '3 days'),
    ('holiday-mini-market', 'Marco', 'Silva', 'marco.silva@example.test', '702-555-0115', 'North Star Leather', '@northstarleather', 'https://example.test/north-star', 'Handmade', 'Wallets, wristlets, tooled keychains, and leather ornaments.', '$15 - $120', 'standard', false, null, 'waitlisted', null, 'unpaid', null, null, now() - interval '2 days'),
    ('holiday-mini-market', 'Pia', 'Ramirez', 'pia.ramirez@example.test', '702-555-0116', 'Kitsch Kitchen', '@kitschkitchenlv', null, 'Vintage', 'Vintage glassware, cookbooks, linens, and holiday tabletop pieces.', '$6 - $90', 'standard', false, null, 'approved', null, 'waived', null, null, now() - interval '2 days'),
    ('sweetheart-swap', 'Elle', 'Waters', 'elle.waters@example.test', '702-555-0117', 'Love Sick Florals', '@lovesickflorals', 'https://example.test/love-sick', 'Handmade', 'Mini bouquets, dried flower bundles, and wearable flower pins.', '$12 - $75', 'standard', false, 'Would like end cap for bouquet buckets.', 'pending', null, 'unpaid', null, null, now() - interval '1 day'),
    ('sweetheart-swap', 'Kai', 'Nguyen', 'kai.nguyen@example.test', '702-555-0118', 'Second Date Vintage', '@seconddatevintage', null, 'Vintage', 'Romantic vintage slips, jackets, handbags, and date-night styling.', '$20 - $150', 'standard', false, null, 'pending', null, 'unpaid', null, null, now() - interval '20 hours'),
    ('sweetheart-swap', 'Mara', 'Stone', 'mara.stone@example.test', '702-555-0119', 'XO Press', '@xopress', 'https://example.test/xo-press', 'Art', 'Letterpress cards, love notes, mini prints, and matchbook poems.', '$5 - $40', 'shared', false, null, 'approved', null, 'paid', 'FAKE-1008', now() - interval '1 hour', now() - interval '18 hours'),
    ('summer-sidewalk-market', 'Theo', 'Banks', 'theo.banks@example.test', '702-555-0120', 'Neon Relics', '@neonrelics', null, 'Collectibles', 'Vintage Vegas ephemera, matchbooks, postcards, and casino collectibles.', '$8 - $200', 'standard', false, null, 'approved', 'Past event sample.', 'paid', 'FAKE-1009', now() - interval '70 days', now() - interval '90 days')
) as vendors (
  event_slug,
  first_name,
  last_name,
  email,
  phone,
  business_name,
  instagram,
  website,
  category,
  product_description,
  price_range,
  booth_type,
  electricity_required,
  special_requests,
  status,
  admin_notes,
  payment_status,
  payment_reference,
  paid_at,
  created_at
)
join public.events on events.slug = vendors.event_slug;
